[tool.poetry]
name = "vocabulary-drills"
version = "0.0.0"
description = ""
authors = ["Suyeon Kang <suyeon.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.115.7"
uvicorn = "^0.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
